#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server:

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

f_path=$1
ip=$2
u_name=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$f_path" "$u_name@$ip:~/"
