#!/usr/bin/env bash
# installs Nginx and configures it to listen to port 80

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
