#!/usr/bin/env bash
# Installs and configures HAProxy in a load balancer server

# Replace [STUDENT_ID] with your actual student ID or desired hostname prefix
STUDENT_ID="114411"

# Define web server IP addresses
WEB_SERVER_1_IP="54.236.26.181" 
WEB_SERVER_2_IP="52.91.117.65"

# Install HAProxy and dependencies
apt-get update
apt-get install -y haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

frontend web
    bind *:80
    mode http
    default_backend servers

backend servers
    mode http
    balance roundrobin
    server web-01 $STUDENT_ID-web-01:$WEB_SERVER_1_IP:80 check
    server web-02 $STUDENT_ID-web-02:$WEB_SERVER_2_IP:80 check

    # Set custom response header
    http-response set-header X-Served-By %[dst]
EOF

# Enable HAProxy init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
service haproxy restart
