#!/bin/bash
# A Bash script that transfers a file from our clinet to a server

if [ $# -lt 4 ]; then
    echo "Usage:  $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
elif [ "$#" -lt 4 ]; then
    scp -0 StrictHostKeyChecking=no "$1" "$3@$2":~/
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi