#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
# display all processes, for all users, including those which might not have a TTY
# show process hierarchy
# display in a user-oriented format
ps -ef --forest
