#!/usr/bin/env bash
# superstiotios numbers

for x in {1..20}
do
    echo "$x"
    if [ "$x" -eq 4 ]
    then
        echo "bad luck from China"
    elif [ "$x" -eq 9 ]
    then    
        echo "bad luck from Japan"
    elif [ "$x" -eq 17 ]
    then
        echo "bad luck from Italy"
    fi
done
