#!/usr/bin/env bash
# checks a files existance

if [ -f "$PWD/school" ]; then
    echo "school file exists"
    if test -s "$PWD/school"; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if test -f "$PWD/school"; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
